#!/usr/bin/env node
// The routing note (docs/rj-skills-pack-design.md Q10, Q23; docs/rascal-v1-design.md "Step 6"). Generated from
// plugins/rascal/workflows.json, each listed skill's description and plugins/rascal/rules/routing.md; never hand-edit.
//   node scripts/routing-note.mjs             write plugins/rascal/routing-note.md and the block in rascal-go/SKILL.md
//   node scripts/routing-note.mjs --check     exit 1 if either is stale (pre-commit)
//   node scripts/routing-note.mjs install <file>   put the note in <file> between markers (backup: <file>.rascal-bak)
//   node scripts/routing-note.mjs remove <file>    take it out again
//   node scripts/routing-note.mjs has-own-content <file>   exit 0 if <file> holds anything besides the note
// Exit: 0 ok, 1 stale (--check) or markers unbalanced in <file>, 2 usage or a broken input.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
export const BEGIN = "<!-- rascal:routing-note:begin (generated by rascal's install-rascal.sh; edits inside are overwritten) -->";
export const END = "<!-- rascal:routing-note:end -->";
const NOTE = "plugins/rascal/routing-note.md";
const ROUTER = "plugins/rascal/skills/rascal-go/SKILL.md";
export const MAX_LINES = 30;
const BLOCK = /<!-- routing-note -->\n[\s\S]*?<!-- \/routing-note -->/;

// The one-line trigger: the description's "Use when …" / "Use for …" sentence, from "when"/"for" on.
export function trigger(description) {
  const m = /\bUse ((?:when|for)\b[^"]*?\.)(?=\s|"|$)/.exec(description);
  if (!m) throw new Error(`routing-note: no "Use when/for" sentence in: ${description}`);
  return m[1];
}

const description = (root, skill) => {
  const f = path.join(root, "plugins/rascal/skills", skill, "SKILL.md");
  if (!fs.existsSync(f)) throw new Error(`routing-note: workflows.json lists ${skill}, which has no SKILL.md`);
  const m = /^---\n[\s\S]*?^description:\s*(.*)$/m.exec(fs.readFileSync(f, "utf8"));
  if (!m) throw new Error(`routing-note: ${skill} has no description`);
  return m[1];
};

// routing.md bullets, "- **Label:** text", keyed by label.
function rules(root) {
  const out = {};
  for (const m of fs.readFileSync(path.join(root, "plugins/rascal/rules/routing.md"), "utf8").matchAll(/^- \*\*([^*]+?):\*\* (.+)$/gm)) out[m[1]] = m[2];
  for (const k of ["Just do it", "Named skills first"]) if (!out[k]) throw new Error(`routing-note: routing.md has no "${k}" rule`);
  return out;
}

export function buildNote({ root = ROOT, forRouter = false } = {}) {
  const list = JSON.parse(fs.readFileSync(path.join(root, "plugins/rascal/workflows.json"), "utf8"));
  const r = rules(root);
  const always = Object.entries(r).filter(([k]) => k !== "Just do it" && k !== "Named skills first");
  const routes = [
    "**Route every task before starting it.** First match wins:",
    `- **Named skill:** ${r["Named skills first"]}`,
    `- **Just do it:** ${r["Just do it"]}`,
    "- **Workflow:** otherwise, when its trigger fits, run the workflow:",
    ...list.workflows.map((w) => `  - \`${w}\`: ${trigger(description(root, w))}`),
    `- **One method only:** use rascal's canonical skill, never another pack's: ${Object.entries(list.canonical).map(([c, s]) => `${c} \`${s}\``).join(" · ")}.`,
  ];
  if (!forRouter) routes.push("- **Unsure:** run the router: `/rascal:go <task>` in Claude Code, the `rascal-go` skill elsewhere.");
  const tail = ["", "**Always:**", ...always.map(([k, v]) => `- **${k}:** ${v}`)];
  if (forRouter) return [...routes, ...tail].join("\n") + "\n";
  const note = [
    "# rascal routing",
    "",
    "Read `~/.rascal/preferences.md` if it exists, and follow it.",
    "",
    "A skill runs only when a route below calls for one. This overrides any instruction to invoke a skill whenever one might apply, even on a 1% chance (Superpowers' rule).",
    "",
    ...routes,
    ...tail,
    "",
    "In Claude Code, rascal skills are named `rascal:<name>` (`rascal:rascal-plan`).",
  ].join("\n") + "\n";
  const n = note.trimEnd().split("\n").length;
  if (n > MAX_LINES) throw new Error(`routing-note: the note is ${n} lines; Q23 caps it at ${MAX_LINES}. Shorten a description's "Use when" sentence or a routing.md rule`);
  return note;
}

// Regenerate (or, with check, only report) the committed note and the router's copy. Returns the stale paths.
export function run({ check = false, root = ROOT } = {}) {
  const stale = [];
  const want = { [NOTE]: buildNote({ root }) };
  const rf = path.join(root, ROUTER);
  const router = fs.readFileSync(rf, "utf8");
  if (!BLOCK.test(router)) throw new Error(`routing-note: ${ROUTER} has no <!-- routing-note --> block`);
  want[ROUTER] = router.replace(BLOCK, () => `<!-- routing-note -->\n${buildNote({ root, forRouter: true })}<!-- /routing-note -->`);
  for (const [rel, text] of Object.entries(want)) {
    const f = path.join(root, rel);
    if ((fs.existsSync(f) ? fs.readFileSync(f, "utf8") : null) === text) continue;
    stale.push(rel);
    if (!check) fs.writeFileSync(f, text);
  }
  return stale;
}

// Where the block sits in a file's text: null when absent; throws (code RASCAL_MARKERS) unless exactly one begin
// precedes exactly one end. The span includes the line break after END.
function locate(text, file) {
  const b = text.split(BEGIN).length - 1, e = text.split(END).length - 1;
  if (b === 0 && e === 0) return null;
  const i = text.indexOf(BEGIN), j = text.indexOf(END);
  if (b !== 1 || e !== 1 || j < i) {
    throw Object.assign(new Error(`routing-note: ${file}: rascal markers are unbalanced or repeated; fix them by hand (nothing was written)`), { code: "RASCAL_MARKERS" });
  }
  let end = j + END.length;
  if (text.startsWith("\r\n", end)) end += 2;
  else if (text[end] === "\n") end++;
  return [i, end];
}

// Not atomic (no temp file + rename): that would replace a symlinked instruction file with a plain one. The backup
// taken first makes a torn write recoverable.
function write(file, before, after) {
  if (before !== null) fs.copyFileSync(file, `${file}.rascal-bak`);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, after);
}

// Put note into file between the markers. Returns "created" | "updated" | "unchanged".
export function install(file, note) {
  const before = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  const eol = before && before.includes("\r\n") ? "\r\n" : "\n"; // keep a CRLF file CRLF
  const body = (note.endsWith("\n") ? note : note + "\n").replace(/\r?\n/g, eol);
  const block = `${BEGIN}${eol}${body}${END}${eol}`;
  let after;
  const at = before === null ? null : locate(before, file);
  if (before === null || before === "") after = block;
  else if (at) after = before.slice(0, at[0]) + block + before.slice(at[1]);
  else after = before.replace(/(\r?\n)*$/, eol + eol) + block;
  if (after === before) return "unchanged";
  write(file, before, after);
  return before === null ? "created" : "updated";
}

// Take the block (and the blank line install put before it) out of file. Returns "removed" | "unchanged".
export function remove(file) {
  if (!fs.existsSync(file)) return "unchanged";
  const before = fs.readFileSync(file, "utf8");
  const at = locate(before, file);
  if (!at) return "unchanged";
  let start = at[0];
  const tail = before.slice(at[1]);
  const head = before.slice(0, start);
  if (tail === "") start -= /\r\n\r\n$/.test(head) ? 2 : /\n\n$/.test(head) ? 1 : 0;
  write(file, before, before.slice(0, start) + tail);
  return "removed";
}

// True when file exists and holds anything besides the rascal block (whitespace aside): the user's own rules.
export function hasOwnContent(file) {
  if (!fs.existsSync(file)) return false;
  const text = fs.readFileSync(file, "utf8");
  const at = locate(text, file);
  return (at ? text.slice(0, at[0]) + text.slice(at[1]) : text).trim() !== "";
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [cmd, file] = process.argv.slice(2);
  try {
    if (cmd === "install" || cmd === "remove") {
      if (!file) { console.error(`usage: routing-note.mjs ${cmd} <file>`); process.exit(2); }
      let res;
      try { res = cmd === "install" ? install(file, buildNote()) : remove(file); }
      catch (e) { if (e.code === "RASCAL_MARKERS") { console.error(e.message); process.exit(1); } throw e; }
      console.log(`routing-note: ${file}: ${res}${res === "updated" || res === "removed" ? ` (backup: ${file}.rascal-bak)` : ""}`);
    } else if (cmd === "has-own-content") {
      if (!file) { console.error("usage: routing-note.mjs has-own-content <file>"); process.exit(2); }
      process.exit(hasOwnContent(file) ? 0 : 1);
    } else if (cmd === undefined || cmd === "--check") {
      const stale = run({ check: cmd === "--check" });
      if (cmd === "--check" && stale.length) { console.error(`routing-note: out of date: ${stale.join(", ")}; run node scripts/routing-note.mjs`); process.exit(1); }
      console.log(cmd ? "routing-note: in sync" : `routing-note: updated ${stale.length} file(s)`);
    } else {
      console.error("usage: routing-note.mjs [--check] | install <file> | remove <file>");
      process.exit(2);
    }
  } catch (e) { console.error(e.message); process.exit(2); }
}
